
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.ImageObserver;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author F_ALI
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        q2 = new javax.swing.JButton();
        q3 = new javax.swing.JButton();
        q1 = new javax.swing.JButton();
        q4 = new javax.swing.JButton();
        q5 = new javax.swing.JButton();
        scorefinal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        v1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        v2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        v3 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        v14 = new javax.swing.JButton();
        v24 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        b6 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(783, 478));
        setMinimumSize(new java.awt.Dimension(783, 478));

        jPanel1.setMaximumSize(new java.awt.Dimension(783, 478));
        jPanel1.setMinimumSize(new java.awt.Dimension(783, 478));
        jPanel1.setPreferredSize(new java.awt.Dimension(783, 478));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Questions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        q2.setText("Question 2");
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        q3.setText("Question 3");
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        q1.setText("Question 1");
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        q4.setText("Question 4");
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        q5.setText("Question 5");
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });

        scorefinal.setText("Voir Score");
        scorefinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorefinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorefinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(scorefinal))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 1"));
        jPanel4.setMaximumSize(new java.awt.Dimension(560, 335));
        jPanel4.setMinimumSize(new java.awt.Dimension(560, 335));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(560, 335));
        jPanel4.setLayout(null);

        v1.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\Actions-dialog-ok-apply-icon.png")); // NOI18N
        v1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v1MouseClicked(evt);
            }
        });
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });
        jPanel4.add(v1);
        v1.setBounds(70, 260, 40, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "13", "14", "15", "16", "17" }));
        jPanel4.add(c1);
        c1.setBounds(70, 210, 50, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Combien y a-t-il de carré  ?");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(150, 70, 180, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\test - Copy (2).jpg")); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 10, 530, 340);

        jPanel3.add(jPanel4, "card3");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 2"));
        jPanel5.setMaximumSize(new java.awt.Dimension(560, 395));
        jPanel5.setMinimumSize(new java.awt.Dimension(560, 395));
        jPanel5.setPreferredSize(new java.awt.Dimension(560, 395));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Calculer");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(190, 70, 60, 13);
        jPanel5.add(t2);
        t2.setBounds(390, 350, 50, 30);

        v2.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\Actions-dialog-ok-apply-icon.png")); // NOI18N
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });
        jPanel5.add(v2);
        v2.setBounds(450, 350, 30, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 255));
        jLabel10.setText("Le Prduit des pièces droites - la somme des pièces gauche =");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 360, 370, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\27.png")); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(300, 204));
        jLabel4.setPreferredSize(new java.awt.Dimension(380, 244));
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 0, 550, 360);

        jPanel3.add(jPanel5, "card2");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 3"));
        jPanel6.setMaximumSize(new java.awt.Dimension(570, 355));
        jPanel6.setMinimumSize(new java.awt.Dimension(570, 355));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(570, 355));
        jPanel6.setLayout(null);

        v3.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\Actions-dialog-ok-apply-icon.png")); // NOI18N
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });
        jPanel6.add(v3);
        v3.setBounds(300, 340, 40, 30);
        jPanel6.add(t3);
        t3.setBounds(240, 340, 40, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Combien y a il de différences");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(140, 70, 190, 15);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\test - Copy (3).jpg")); // NOI18N
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 10, 540, 330);

        jPanel3.add(jPanel6, "card3");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 4"));
        jPanel7.setMaximumSize(new java.awt.Dimension(560, 335));
        jPanel7.setMinimumSize(new java.awt.Dimension(560, 335));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(560, 335));
        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Qui pèse plus ?");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(170, 80, 110, 15);

        v14.setText("1");
        v14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v14ActionPerformed(evt);
            }
        });
        jPanel7.add(v14);
        v14.setBounds(140, 350, 40, 23);

        v24.setText("2");
        v24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v24ActionPerformed(evt);
            }
        });
        jPanel7.add(v24);
        v24.setBounds(400, 350, 40, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\25.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(560, 335));
        jLabel8.setMinimumSize(new java.awt.Dimension(560, 335));
        jLabel8.setPreferredSize(new java.awt.Dimension(560, 335));
        jPanel7.add(jLabel8);
        jLabel8.setBounds(10, 20, 550, 330);

        jPanel3.add(jPanel7, "card3");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 5"));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.setMaximumSize(new java.awt.Dimension(560, 335));
        jPanel8.setMinimumSize(new java.awt.Dimension(560, 335));
        jPanel8.setPreferredSize(new java.awt.Dimension(560, 335));
        jPanel8.setLayout(null);

        b6.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\Actions-dialog-ok-apply-icon.png")); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel8.add(b6);
        b6.setBounds(250, 170, 57, 33);

        g.add(r1);
        r1.setText("1");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel8.add(r1);
        r1.setBounds(70, 350, 40, 23);

        g.add(r2);
        r2.setText("2");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel8.add(r2);
        r2.setBounds(200, 350, 40, 23);

        g.add(r3);
        r3.setText("3");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel8.add(r3);
        r3.setBounds(320, 350, 40, 23);

        g.add(r4);
        r4.setText("4");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel8.add(r4);
        r4.setBounds(450, 350, 40, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Quelle est la déffirente ?");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(150, 60, 150, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\F_ALI\\Documents\\NetBeansProjects\\SmartKid\\26.png")); // NOI18N
        jPanel8.add(jLabel7);
        jLabel7.setBounds(10, 10, 530, 350);

        jPanel3.add(jPanel8, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 static int score=0;
    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // remove
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        // add
         jPanel3.add(jPanel5);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // remove
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        // add
         jPanel3.add(jPanel6);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_q3ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
         // remove
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        // add
         jPanel3.add(jPanel4);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_q1ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
         // remove
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        // add
         jPanel3.add(jPanel7);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_q4ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
         // remove
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        // add
         jPanel3.add(jPanel8);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_q5ActionPerformed

    private void v1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v1MouseClicked
     
    }//GEN-LAST:event_v1MouseClicked

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
           String value=c1.getSelectedItem().toString();
        if(value.equals("16")){
        score++;
        v1.setEnabled(false);
        }else
            v1.setEnabled(false);
    }//GEN-LAST:event_v1ActionPerformed

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed
        String v = t2.getText();
        if (t2.getText().equals("")){
                JOptionPane.showMessageDialog(jPanel6, "Entrer une réponse ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(v.equals("109")){
        score++;
        v2.setEnabled(false);
        }else
            v2.setEnabled(false);
    }//GEN-LAST:event_v2ActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        String v1 = t3.getText();
        if (t3.getText().equals("")){
                JOptionPane.showMessageDialog(jPanel7, "Entrer une réponse ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(v1.equals("10")){
        score++;
        v3.setEnabled(false);
        }else
            v3.setEnabled(false);
    }//GEN-LAST:event_v3ActionPerformed

    private void v14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v14ActionPerformed
       score ++;
       v14.setEnabled(false);
       v24.setEnabled(false);
       System.out.println(score);
    }//GEN-LAST:event_v14ActionPerformed

    private void v24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v24ActionPerformed
         v14.setEnabled(false);
       v24.setEnabled(false);
    }//GEN-LAST:event_v24ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        score++;  
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        b6.setEnabled(false);
        r1.setEnabled(false);
        r2.setEnabled(false);
        r3.setEnabled(false);
        r4.setEnabled(false);
    }//GEN-LAST:event_b6ActionPerformed

    private void scorefinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorefinalActionPerformed
        String n= Bienvenue.nom;
        JOptionPane.showMessageDialog(jPanel8, n+"  Votre score  est "+score, "Score Final sur 5", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_scorefinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b6;
    private javax.swing.JComboBox c1;
    private javax.swing.ButtonGroup g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton q1;
    private javax.swing.JButton q2;
    private javax.swing.JButton q3;
    private javax.swing.JButton q4;
    private javax.swing.JButton q5;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JButton scorefinal;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JButton v1;
    private javax.swing.JButton v14;
    private javax.swing.JButton v2;
    private javax.swing.JButton v24;
    private javax.swing.JButton v3;
    // End of variables declaration//GEN-END:variables
}
